# The URL the site will be built for
base_url = "https://zzmzaw.dev"

# The site title for the default language
title = "ZzMzaw's blog"
author = "ZzMzaw"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "tabi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The taxonomies to be rendered for the site and their configuration for the default languages
taxonomies = [
   {name = "tags", feed = true},
]

[search]
# Whether to include the title of the page/section in the index.
include_title = true
# Whether to include the description of the page/section in the index.
include_description = true
# Whether to include the path of the page/section in the index.
include_path = true
# Whether to include the rendered content of the page/section in the index.
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100
# Wether to produce the search index as a javascript file or as a JSON file.
# Accepted value "elasticlunr_javascript" or "elasticlunr_json".
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[languages.fr]
# The site title for the french version
title = "Le blog de ZzMzaw"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index for the french version
build_search_index = true

# The taxonomies to be rendered for the site and their configuration for the french version
taxonomies = [
   {name = "tags", feed = true},
]

[extra]
# The theme's skin
skin = "lavender"

# List additional stylesheets to load site-wide.
# These stylesheets should be located in your site's `static` or `sass` directories.
# Example: stylesheets = ["extra1.css", "path/extra2.css"]
# You can load a stylesheet for a single post by adding it to the [extra] section of the post's front matter, following this same format.
stylesheets = ["cc.css"]

# The menu links in the header
menu = [
  { name = "posts", url = "posts", tailing_slash = true},
  { name = "archive", url = "archive", tailing_slash = true},
  { name = "tags", url = "tags", tailing_slash = true},
]

# The icons available can be found in "social_icons" in the "static" folder.
socials = [
    { name = "github", url = "https://github.com/ZzMzaw", icon = "github" },
    { name = "gitlab", url = "https://gitlab.com/ZzMzaw", icon = "gitlab" },
    { name = "matrix", url = "https://matrix.to/#/@zzmzaw:zzmzaw.dev", icon = "matrix" },
    { name = "discord", url = "https://discordapp.com/users/1199491352623337594", icon = "discord" },
    { name = "rootme", url = "https://www.root-me.org/ZzMzaw", icon = "rootme" },
    { name = "hackthebox", url = "https://app.hackthebox.com/users/1823204", icon = "hackthebox" },
    { name = "hacker-news", url = "https://news.ycombinator.com/user?id=zzmzaw", icon = "hacker-news" },
    { name = "reddit", url = "https://www.reddit.com/user/ZzMzaw", icon = "reddit" },
    { name = "stack-overflow", url = "https://stackoverflow.com/users/23289335/zzmzaw", icon = "stack-overflow" },
    { name = "xda", url = "https://xdaforums.com/m/zzmzaw.11836937/", icon = "xda" },
    # { name = "bitcoin", url = "toto", icon = "bitcoin" },
    # { name = "paypal", url = "toto", icon = "paypal" },
]

# Extra menu to show on the footer, below socials section.
footer_menu = [
    {url = "about", name = "about", trailing_slash = true},
    {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
]

# Enable a copyright notice for the footer, shown between socials and the "Powered by" text.
# $TITLE will be replaced by the website's title.
# You can use $CURRENT_YEAR to automatically insert the current year.
# $SEPARATOR will be replaced by the `separator` variable.
# Markdown is supported (links, emphasis, etc).
copyright = "[$TITLE](https://zzmzaw.dev) © $CURRENT_YEAR by [$AUTHOR](https://zzmzaw.dev/about) is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) ![Creative Commons logo](/img/cc/cc.svg#cc) ![Creative Commons By icon](/img/cc/by.svg#cc) ![Creative Commons SA icon](/img/cc/sa.svg#cc)"

# If `translate_copyright` is set to true, `copyright_translations` can be empty but must exist.
# A build time error will be raised otherwise in order to make sure people already using previous translation method (i18n files) won't forgot to move translations back in config.toml.
# If a translation is missing for language, the `copyright` value will be used instead.
copyright_translations.fr = "[$TITLE](https://zzmzaw.dev/fr) © $CURRENT_YEAR par [$AUTHOR](https://zzmzaw.dev/fr/about) est sous licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) ![Creative Commons logo](/img/cc/cc.svg#cc) ![Creative Commons By icon](/img/cc/by.svg#cc) ![Creative Commons SA icon](/img/cc/sa.svg#cc)"

